cmake_minimum_required(VERSION 3.10)
project(CodeWithCPP)

add_subdirectory(examples/2d-array)
add_subdirectory(examples/array)
add_subdirectory(examples/basic-c)
add_subdirectory(examples/chararray)
add_subdirectory(examples/classes-objects)
add_subdirectory(examples/controlflowstatemwnt)
add_subdirectory(examples/functions)
add_subdirectory(examples/input)
add_subdirectory(examples/local-global-variable)
add_subdirectory(examples/loops)
add_subdirectory(examples/operators)
add_subdirectory(examples/opps)
add_subdirectory(examples/passbyvalue-and-refrence)
add_subdirectory(examples/pointers)
add_subdirectory(examples/reference-variable)
add_subdirectory(examples/string)
add_subdirectory(examples/ternaryopertaors)
add_subdirectory(examples/variable-datatypes)
add_subdirectory(problems/questions)
